# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Xingfan Xia"
subtitle: "See the world from another angle"
author: "Xingfan Xia"
header:
  title: "Photography"
  subtitle: "by Xingfan Xia"
footer:
  name: "Hey there, my name is Xingfan"
  bio: "I like photography because it exposed another angle to view the world around us"
  github: 'Check out @<a href="https://xiax.ai">my site</a> to know more about me! ;)'
web_design: "X.X."
social_urls:
  # facebook: ""
  # twitter: ""
  # instagram: ""
  # dribbble: ""
  linkedin: "https://www.linkedin.com/in/xingfanxia/"
  github: "https://github.com/xingfanxia/"
